import { FoodLoopMark } from '../../components/brand/FoodLoopMark'

const LABEL = 'QR preview — generated by backend in production'

// Finder-square corners only. The interior is deliberately contour art, not modules: this does NOT
// encode the token and must never be presented as scannable. The backend renders the real QR.
const FINDERS: [number, number][] = [
  [0, 0],
  [22, 0],
  [0, 22],
]

export function QrPreview() {
  return (
    // The visible caption is the accessible description; the art itself is decorative.
    <figure className="qr">
      <svg viewBox="0 0 29 29" className="qr__art" aria-hidden="true">
        {FINDERS.map(([x, y]) => (
          <g key={`${x}-${y}`} transform={`translate(${x} ${y})`}>
            <rect x="0.5" y="0.5" width="6" height="6" rx="1.4" fill="none" stroke="currentColor" />
            <rect x="2" y="2" width="3" height="3" rx="0.7" fill="currentColor" />
          </g>
        ))}
        {[5, 7.5, 10, 12.5].map((r) => (
          <circle key={r} cx="14.5" cy="14.5" r={r} fill="none" stroke="currentColor" strokeWidth="0.3" strokeDasharray="0.6 0.9" opacity={0.55} />
        ))}
      </svg>
      <span className="qr__center" aria-hidden="true">
        <FoodLoopMark />
      </span>
      <figcaption className="qr__caption">{LABEL}</figcaption>
    </figure>
  )
}
